/* const scorecard = {
  team1: {
    name: "India",
    players: [
      {
        name: "Virat Kohli",
        runsScored: 56,
        ballsFaced: 38,
        fours: 7,
        sixes: 0,
        dismissals: [],
      },
      {
        name: "Rohit Sharma",
        runsScored: 63,
        ballsFaced: 45,
        fours: 8,
        sixes: 2,
        dismissals: [{ bowler: "Bumrah", dismissalType: "caught" }],
      },
      // more players
    ],
    overs: 20,
    wickets: 10,
    runs: 200,
  },
  team2: {
    name: "Australia",
    players: [
      {
        name: "Steve Smith",
        runsScored: 71,
        ballsFaced: 54,
        fours: 9,
        sixes: 1,
        dismissals: [],
      },
      {
        name: "David Warner",
        runsScored: 34,
        ballsFaced: 28,
        fours: 4,
        sixes: 0,
        dismissals: [{ bowler: "Kumar", dismissalType: "lbw" }],
      },
      // more players
    ],
    overs: 20,
    wickets: 10,
    runs: 180,
  },
};

function calculateWinningTeam(scorecard) {
  const { team1, team2 } = scorecard;
  if (team1.runs > team2.runs) {
    return team1.name;
  } else if (team2.runs > team1.runs) {
    return team2.name;
  } else {
    return "It's a tie!";
  }
}

function printScorecard(scorecard) {
  console.log(`${scorecard.team1.name} vs ${scorecard.team2.name}`);
  console.log("---");
  console.log(`${scorecard.team1.name} - ${scorecard.team1.runs}/${scorecard.team1.wickets} (${scorecard.team1.overs} overs)`);
  console.log("Player\t\t\tRuns\tBalls\t4s\t6s\tDismissal");
  scorecard.team1.players.forEach((player) => {
    console.log(
      `${player.name}\t\t\t${player.runsScored}\t${player.ballsFaced}\t${player.fours}\t${player.sixes}\t${player.dismissals.length > 0 ? player.dismissals[0].dismissalType : "not out"}`
    );
  });
  console.log("---");
  console.log(`${scorecard.team2.name} - ${scorecard.team2.runs}/${scorecard.team2.wickets} (${scorecard.team2.overs} overs)`);
  console.log("Player\t\t\tRuns\tBalls\t4s\t6s\tDismissal");
  scorecard.team2.players.forEach((player) => {
    console.log(
      `${player.name}\t\t\t${player.runsScored}\t${player.ballsFaced}\t${player.fours}\t${player.sixes}\t${player.dismissals.length > 0 ? player.dismissals[0].dismissalType : "not out"}`
    );
  });
  console.log("---");
  console.log(`Result: ${calculateWinningTeam(scorecard)}`);
}

printScorecard(scorecard);
 */

// id
// name
// totalOver
// venue
// date
// tossWinner
// tossChoice
// matchWinner

// "name": "Western Australia vs New South Wales, Final",
// "matchType": "odi",
// "status": "Western Australia won by 18 runs",
// "venue": "Junction Oval, Melbourne",
// "date": "2022-03-10",
// "tossWinner": "Western Australia",
// "tossChoice": "bat",
// "matchWinner": "Western Australia"

const matchData = [
  {
    name: "Bangladesh vs India Cricket Match",
    tossChoice: "Bat",
    tossWinner: "BD",
    totalOver: "10",
    venue: "Dhaka",
    date: "2023-05-04",
    status: "BD won by 18 runs",
    matchWinner: "Bangladesh",
    team1: {
      name: "India",
      captain: {
        name: "",
        type: "",
        runsScored: 0,
        ballsFaced: 0,
        fours: 0,
        sixes: 0,
        dismissals: [],
        wicketsTaken: 0,
        oversBowled: 0,
        runsConceded: 0,
        economyRate: 0,
        strikeRate: 0,
      },
      players: [
        {
          name: "",
          type: "",
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: "",
          type: "",
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
      ],
      overs: 20,
      wickets: 10,
      runs: 200,
    },
    team2: {
      name: "Bangladesh",
      captain: {
        name: "",
        type: "",
        runsScored: 0,
        ballsFaced: 0,
        fours: 0,
        sixes: 0,
        dismissals: [],
        wicketsTaken: 0,
        oversBowled: 0,
        runsConceded: 0,
        economyRate: 0,
        strikeRate: 0,
      },
      players: [
        {
          name: "",
          type: "",
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: "",
          type: "",
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
      ],
      overs: 20,
      wickets: 10,
      runs: 200,
    },
  },
];

const onSubmit = (data) => {
  const newMatchData = {
    name: `${data.teamA} vs ${data.teamB} Cricket Match`,
    tossChoice: data.tossChoice,
    tossWinner: data.tossWinner === "teamA" ? data.teamA : data.teamB,
    totalOver: data.totalOver,
    venue: data.venue,
    date: data.date,
    status: "", // Replace with the actual result
    matchWinner: "", // Replace with the actual match winner
    team1: {
      name: data.teamA,
      captain: {
        name: data.teamACaptainName,
        type: data.teamACaptainType,
        runsScored: 0,
        ballsFaced: 0,
        fours: 0,
        sixes: 0,
        dismissals: [],
        wicketsTaken: 0,
        oversBowled: 0,
        runsConceded: 0,
        economyRate: 0,
        strikeRate: 0,
      },
      players: [
        {
          name: data.teamAPlayerName1,
          type: data.teamAPlayerType1,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName2,
          type: data.teamAPlayerType2,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName3,
          type: data.teamAPlayerType3,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName4,
          type: data.teamAPlayerType4,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName5,
          type: data.teamAPlayerType5,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName6,
          type: data.teamAPlayerType6,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName7,
          type: data.teamAPlayerType7,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName8,
          type: data.teamAPlayerType8,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName9,
          type: data.teamAPlayerType9,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamAPlayerName10,
          type: data.teamAPlayerType10,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
      ],
      overs: 0,
      wickets: 0,
      runs: 0,
    },
    team2: {
      name: data.teamB,
      captain: {
        name: data.teamBCaptainName,
        type: data.teamBCaptainType,
        runsScored: 0,
        ballsFaced: 0,
        fours: 0,
        sixes: 0,
        dismissals: [],
        wicketsTaken: 0,
        oversBowled: 0,
        runsConceded: 0,
        economyRate: 0,
        strikeRate: 0,
      },
      players: [
        {
          name: data.teamBPlayerName1,
          type: data.teamBPlayerType1,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName2,
          type: data.teamBPlayerType2,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName3,
          type: data.teamBPlayerType3,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName4,
          type: data.teamBPlayerType4,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName5,
          type: data.teamBPlayerType5,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName6,
          type: data.teamBPlayerType6,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName7,
          type: data.teamBPlayerType7,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName8,
          type: data.teamBPlayerType8,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName9,
          type: data.teamBPlayerType9,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
        {
          name: data.teamBPlayerName10,
          type: data.teamBPlayerType10,
          runsScored: 0,
          ballsFaced: 0,
          fours: 0,
          sixes: 0,
          dismissals: [],
          wicketsTaken: 0,
          oversBowled: 0,
          runsConceded: 0,
          economyRate: 0,
          strikeRate: 0,
        },
      ],
      overs: 0,
      wickets: 0,
      runs: 0,
    },
  };
};
